name: aaa_multi
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.4
  - attrs=20.2.0
  - black=19.10b0
  - blas=1.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - click=7.1.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dbus=1.13.16
  - expat=2.2.9
  - flake8=3.8.3
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=1.7.0
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - ninja=1.10.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=1.1.1
  - pathspec=0.7.0
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pycodestyle=2.6.0
  - pyflakes=2.2.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.6.12
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2020.1
  - qt=5.9.7
  - readline=8.0
  - regex=2020.7.14
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.5.0
  - tornado=6.0.4
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - wheel=0.35.1
  - xz=5.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.10.0
    - amply==0.1.2
    - ase==3.20.1
    - cachetools==4.1.1
    - chardet==3.0.4
    - decorator==4.4.2
    - docutils==0.16
    - flake8-import-order==0.18.1
    - future==0.18.2
    - google-auth==1.21.2
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - grpcio==1.32.0
    - h5py==2.10.0
    - idna==2.10
    - iniconfig==1.0.1
    - isodate==0.6.0
    - jinja2==2.11.2
    - joblib==0.16.0
    - lapsolver==1.1.0
    - llvmlite==0.34.0
    - markdown==3.2.2
    - markupsafe==1.1.1
    - more-itertools==8.5.0
    - motmetrics==1.2.0
    - networkx==2.5
    - numba==0.51.2
    - oauthlib==3.1.0
    - packaging==20.4
    - pluggy==0.13.1
    - protobuf==3.13.0
    - pulp==2.3
    - py==1.9.0
    - py-cpuinfo==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytest==6.0.2
    - pytest-benchmark==3.2.3
    - pytorch-lightning==0.9.0
    - pyyaml==5.3.1
    - rdflib==5.0.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.7.0
    - threadpoolctl==2.1.0
    - torch-geometric==1.6.1
    - torch-scatter==2.0.4
    - torch-sparse==0.6.1
    - tqdm==4.49.0
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - xmltodict==0.12.0

